complete rewrite, first working debuglog for `hrx -t`

diff --git a/hrx-2 b/hrx-2
--- a/hrx-2
+++ b/hrx-2
@@ -2,7 +2,7 @@
 set -eu
 
 err() {
-	printf %s\\n >&2 "${0##*/}:$1"
+	printf %s\\n >&2 "${0##*/}: $1"
 	exit "${2-2}"
 }
 log() {
@@ -37,9 +37,85 @@ done
 shift $((OPTIND - 1))
 
 
-path_chars_blacklist=$(printf \\x)
+# path-character ::= any character other than
+# U+0000 through U+001F
+#  0 	0 	000 		NUL #  no need to/can't detect, shell scripts does no support it. native shell eror may be printed (if the shell has implemented it)
+#  1 	1 	001 		SOH
+#  2 	2 	002 		STX
+#  3 	3 	003 		ETX
+#  4 	4 	004 		EOT
+#  5 	5 	005 		ENQ
+#  6 	6 	006 		ACK
+#  7 	7 	007 		BEL
+#  8 	8 	010 		BS
+#  9 	9 	011 		TAB
+#  10 	A 	012 		LF
+#  11 	B 	013 		VT
+#  12 	C 	014 		FF
+#  13 	D 	015 		CR
+#  14 	E 	016 		SO
+#  15 	F 	017 		SI
+#  16 	10 	020 		DLE
+#  17 	11 	021 		DC1
+#  18 	12 	022 		DC2
+#  19 	13 	023 		DC3
+#  20 	14 	024 		DC4
+#  21 	15 	025 		NAK
+#  22 	16 	026 		SYN
+#  23 	17 	027 		ETB
+#  24 	18 	030 		CAN
+#  25 	19 	031 		EM
+#  26 	1A 	032 		SUB
+#  27 	1B 	033 		ESC
+#  28 	1C 	034 		FS
+#  29 	1D 	035 		GS
+#  30 	1E 	036 		RS
+#  31 	1F 	037 		US
+# ,
+# DEL U+007F DELETE,
+# '/' U+002F SOLIDUS, # used as path separator (wont detect)
+# ':' U+003A COLON or
+# '\' U+005C REVERSE SOLIDUS
+path_chars_blacklist=$(
+printf \
+\\x01\
+\\x02\
+\\x03\
+\\x04\
+\\x05\
+\\x06\
+\\x07\
+\\x08\
+\\x09\
+\\x0A\
+\\x0B\
+\\x0C\
+\\x0D\
+\\x0E\
+\\x0F\
+\\x10\
+\\x11\
+\\x12\
+\\x13\
+\\x14\
+\\x15\
+\\x16\
+\\x17\
+\\x18\
+\\x19\
+\\x1A\
+\\x1B\
+\\x1C\
+\\x1D\
+\\x1E\
+\\x1F\
+\
+\\x3A\
+\\x5C\
+;
+)
 in_line() {
-	printf %s ", in line $line_num: $line"
+	printf %s "${1-, }in line $line_num: '$line'"
 }
 
 parsing_err() {
@@ -47,8 +123,53 @@ parsing_err() {
 }
 
 # fns:
-hrx_comment() {
-	err todo
+
+hrx_is_notnewentry() {
+	case $1 in "$boundary"|"$boundary "*)
+		return 1
+	esac
+}
+
+# `entry_type` should always be in (dir|file|comment|x_invalid)
+hrx_parse_begin_dir() {
+	log "(debug) fn hrx_parse_begin_dir       got: '$1' ${2-}"
+}
+hrx_parse_begin_file() {
+	log "(debug) fn hrx_parse_begin_file      got: '$1' ${2-}"
+}
+hrx_parse_begin_comment() {
+	log "(debug) fn hrx_parse_begin_comment   got: '$1' ${2-}"
+}
+hrx_parse_begin_x_invalid() {
+	log "(debug) fn hrx_parse_begin_x_invalid got: '$1' ${2-}"
+}
+
+
+hrx_parse_end_dir() {
+	log "(debug) fn hrx_parse_end_dir         got: '$1' ${2-}"
+}
+hrx_parse_end_file() {
+	log "(debug) fn hrx_parse_end_file        got: '$1' ${2-}"
+}
+hrx_parse_end_comment() {
+	log "(debug) fn hrx_parse_end_comment     got: '$1' ${2-}"
+}
+hrx_parse_end_x_invalid() {
+	log "(debug) fn hrx_parse_end_x_invalid   got: '$1' ${2-}"
+}
+
+
+rx_parse_dir() {
+	log "(debug) fn hrx_parse_dir             got: '$1' ${2-}"
+}
+hrx_parse_file() {
+	log "(debug) fn hrx_parse_file            got: '$1' ${2-}"
+}
+hrx_parse_comment() {
+	log "(debug) fn hrx_parse_comment         got: '$1' ${2-}"
+}
+hrx_parse_x_invalid() {
+	log "(debug) fn hrx_parse_x_invalid       got: '$1' ${2-}"
 }
 
 _hrx_parse_boundary() {
@@ -72,60 +193,85 @@ _hrx_parse_boundary() {
 	esac
 }
 
+hrx_get_entry_type() {
+
+	# first time needs to get boundary
+	case ${boundary+x} in '')
+		_hrx_parse_boundary "$line" || { # sets 'boundary'
+			err "mallformed entry, can not parse boundary$(in_line)"
+		}
+	esac
+
+	hrx_get_entry_type() {
+		case $line in
+			"$boundary") entry_type=comment;;
+			"$boundary "*/) entry_type=dir;;
+			"$boundary "?*) entry_type=file;;
+			"$boundary ")
+				log "warning: comment with space before new line / seems like empty path? $(in_line '')"
+				entry_type=comment
+			;;
+			*) parsing_err 2 1;;
+		esac
+
+		case ${action-} in dir|file) # parsing+validate var `path`
+			path=${line#"$boundary "}
+			case $line in "$boundary $path") ;; *)
+				parsing_err 3
+			esac
+
+			while case $path in /*) ;; *) false; esac; do
+				log "note: triming absolute path$(in_line)"
+				path=${path#/}
+			done
+
+			case $path in
+			'../'*|*'/../'*|*'/..'|'..')
+				err "relative paths contaning '..' are not allowed, path='$path'"
+				;;
+
+			'') # expected when trimming '/'|'///'
+				log "empty path, path='$path'$(in_line)"
+				entry_type=x_invalid
+				;;
+			*["$path_chars_blacklist"]*)
+				log "note: found disawolled char, path='$path'"
+				;;
+			esac
+
+		esac
+
+	}
+	hrx_get_entry_type "$@"
+}
+
 hrx_parser() {
 	line_num=0
 	while read -r line; do
 		line_num=$((line_num + 1))
 
-		case ${entry_type-} in
-		dir)
-			case $line in
-				'') ;;
-				*[!" 	"]*) log "warning: mallformed directory etry$(in_line)";;
-			esac
-			;;
-			
-		x)
-			err TODO
-			hrx_"$entry_type" "$line"
-			;;
-		*)
-			_hrx_parse_boundary "$line" || { # sets 'boundary'
-				log "mallformed entry$(in_line)"
+		case ${entry_type-} in '') ;; *)
+			hrx_is_notnewentry "$line" || {
+				hrx_parse_end_"$entry_type" "$line"
+				entry_type=''
 			}
-			case $line in
-				"$boundary") entry_type=comment;;
-				"$boundary "?*/) entry_type=dir;;
-				"$boundary "?*) entry_type=file;;
-				"$boundary ")
-					log "warning: comment with space before new line$(in_line)"
-					entry_type=comment
-				;;
-				*) parsing_err 2 1;;
-			esac
-			
-			case ${action-} in dir|file) # parsing var `path`
-				path=${line#"$boundary "}
-				case $line in "$boundary $path") ;; *)
-					parsing_err 3
-				esac
-				while case $path in /*) ;; *) false; esac; do
-					path=${path#/}
-				done
-				case $path in
-				'')
-					err "empty file/dir name after trimming path$(in_line)"
-					;;
-				*["$path_chars_blacklist"]*)
-					log "note: found disawolled char$(in_line)"
-				esac
-			esac
-
-			case ${action-} in
-				dir)
-			esac
 		esac
+
+		
+		case ${entry_type-} in '')
+			hrx_get_entry_type "$line"
+			hrx_parse_begin_"$entry_type" "$line"
+			continue
+		esac
+
+		# NOTE: `entry_type` should always be in (dir|file|comment|x_invalid)
+		hrx_parse_"$entry_type" "$line"
+
 	done
+
+	case ${entry_type-} in '') ;; *)
+		hrx_parse_end_"$entry_type" "$line" end
+	esac
 
 }
 
@@ -145,9 +291,9 @@ explisit_dirs=0
 main() {
 case ${opt_c+c}${opt_x+x}${opt_t+t} in
 t)
-	err 'hrx -t : NOT IMPLEMENTED, {in progress}'
+	log "NOTE: 'hrx -t' is in progress"
 
-
+	hrx_parser
 
 	#
 	;;
