add (2022-07-26 07:36) ../hrx-b

diff --git a/hrx-2 b/hrx-2
--- a/hrx-2
+++ b/hrx-2
@@ -37,74 +37,22 @@ done
 shift $((OPTIND - 1))
 
 
+path_chars_blacklist=$(printf \\x)
+in_line() {
+	printf %s ", in line $line_num: $line"
+}
+
+parsing_err() {
+	err "parsing error($1)$(in_line)" "${2-4}"
+}
 
 # fns:
-when_empty_archivefile() {
-	case ${1+x} in
-		x) err "archive file is empty" "$1";;
-		*) log "archive file is empty";;
-	esac
+hrx_comment() {
+	err todo
 }
 
-# parging fns:
-case ${opt_v+v} in
-v)
-	hrx_parse_comment() {
-		printf %s\\n "comment:"
-		while read -r line; do
-			case $line in
-				"$boundary"|"$boundary "*) break;;
-				*) printf '  %s\n' "$line";;
-			esac
-		done
-	}
-	;;
-*)
-	hrx_parse_comment() {
-		while read -r line; do
-			case $line in
-				"$boundary"|"$boundary "*) break;;
-			esac
-		done
-	}
-esac
-
-##hrx_parse_entry_test() {
-##	# note: $line var could already be set by fn `hrx_parse_first_boundary`
-##
-##	case ${line+x} in '') read -r line; esac
-##	while :; do
-##		err 'TODO HERE' # TODO:! HERE
-##		case $line in
-##			"$boundary") err TODO;;
-##			""*) err 'parse_name not done'
-##		esac
-##
-##		read -r line || break
-##	done
-##}
-
-hrx_next_path() {
-	case ${1-0} in
-		#1) ;; # use previous var `line` as is
-		0) read -r line;;
-	esac
-	while :; do
-		case $line in
-			"$boundary") hrx_parse_comment || return; continue;; # hrx_parse_comment reads next lines
-			"$boundary "*) path=${line#"$boundary"};;
-			*) err "parse err in line: $line";;
-		esac
-		break
-	done
-}
-
-_hrx_parse__boundary_line() {
-	# requires var `line`
-	# sets var `boundary` or returns 1 or if parsing error throws `err`
-	# temp vars: `_i`
-
-	case $line in
+_hrx_parse_boundary() {
+	case $1 in
 		\<=*\>*) ;;
 		*) return 1;;
 	esac
@@ -119,23 +67,66 @@ _hrx_parse__boundary_line() {
 
 	_i=\<${_i}\>
 	case $line in
-		"$_i"|"$_i "*) boundary=$_i;; # found first boundary
-		*) err "parsing error in line: $line" 4;;
+		"$_i"*) boundary=$_i;; # found first boundary
+		*) parsing_err 1;;
 	esac
 }
-hrx_parse_first_boundary() { # seems to work
-	# reads untill finds first  boundary
-	# note: if first entry is a comment x_path will be unset
-	# note: if empty input / cant find line with boundary, then boundary will be unset
-	# note: will leave $line var to be parsed later on by *(todo fn name)*
 
+hrx_parser() {
+	line_num=0
 	while read -r line; do
-		if _hrx_parse__boundary_line "$line"; then
-			break
-		else
-			log "warning: unexpected line: $line"
-		fi
+		line_num=$((line_num + 1))
+
+		case ${entry_type-} in
+		dir)
+			case $line in
+				'') ;;
+				*[!" 	"]*) log "warning: mallformed directory etry$(in_line)";;
+			esac
+			;;
+			
+		x)
+			err TODO
+			hrx_"$entry_type" "$line"
+			;;
+		*)
+			_hrx_parse_boundary "$line" || { # sets 'boundary'
+				log "mallformed entry$(in_line)"
+			}
+			case $line in
+				"$boundary") entry_type=comment;;
+				"$boundary "?*/) entry_type=dir;;
+				"$boundary "?*) entry_type=file;;
+				"$boundary ")
+					log "warning: comment with space before new line$(in_line)"
+					entry_type=comment
+				;;
+				*) parsing_err 2 1;;
+			esac
+			
+			case ${action-} in dir|file) # parsing var `path`
+				path=${line#"$boundary "}
+				case $line in "$boundary $path") ;; *)
+					parsing_err 3
+				esac
+				while case $path in /*) ;; *) false; esac; do
+					path=${path#/}
+				done
+				case $path in
+				'')
+					err "empty file/dir name after trimming path$(in_line)"
+					;;
+				*["$path_chars_blacklist"]*)
+					log "note: found disawolled char$(in_line)"
+				esac
+			esac
+
+			case ${action-} in
+				dir)
+			esac
+		esac
 	done
+
 }
 
 
@@ -155,17 +146,6 @@ main() {
 case ${opt_c+c}${opt_x+x}${opt_t+t} in
 t)
 	err 'hrx -t : NOT IMPLEMENTED, {in progress}'
-	#
-	case ${opt_b+b} in '')
-		# reads first line(s) untill finds boundary
-		# then sets vars `line` `boundary`
-		hrx_parse_first_boundary || return
-	esac
-
-	
-	###todo: case $# in
-	hrx_next_path
-	###todo: esac
 
 
 
